version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: batchtest_postgres_6543
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: batchtest
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    #      LANG: ja_JP.utf8
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    # 現在のフォルダの下にマウントする
    driver_opts:
      type: none
      device: $PWD/docker/postgres/data
      o: bind
